
version: '3.8'

services:
  # --- Service Java (Cart Service) ---
  cart-service:
#    image: hung004/cart_service_app:v1.0
    build: .
    container_name: cart_service_app
    restart: always
    ports:
      - "9099:9099"
    depends_on:
      - cart-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/cart_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      AUTH_SERVICE_ISSUER_URI: http://localhost:8081

      AUTH_SERVICE_JWK_SET_URI: http://host.docker.internal:8081/oauth2/jwks

      PRODUCT_SERVICE_URL: http://host.docker.internal:8082/api/product

    extra_hosts:
      - "host.docker.internal:host-gateway"

  # --- MySQL (Port 3307) ---
  cart-db:
    image: mysql:8.0
    container_name: cart_db_standalone
    restart: always
    environment:
      MYSQL_DATABASE: cart_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - cart_data:/var/lib/mysql

  # --- Zookeeper (Port 22181) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  # --- Kafka (Port 9094) ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  cart_data: