server:
  port: 8088

spring:
  application:
    name: promotion-discount-service

  datasource:
    url: jdbc:mysql://localhost:3306/promotiondiscount
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # Giữ none để Flyway quản lý schema

  flyway:
    enabled: true
    baseline-on-migrate: true  # Nếu schema đã tồn tại, baseline để tránh lỗi
    locations: classpath:db/migration  # Vị trí migration scripts
    schemas: promotiondiscount

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8081

logging:
  level:
    org.springframework: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
